# ETAPA 2: Servidor Web (Nginx)
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

# NUEVA LÍNEA CLAVE: Copiar tu configuración personalizada de Proxy Inverso
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Configuración de permisos para usuario no-root
RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid /var/cache/nginx /var/log/nginx /usr/share/nginx/html

USER nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]