# ETAPA 1: Build
FROM maven:3.8.5-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# ETAPA 2: Runtime
FROM amazoncorretto:17-alpine
WORKDIR /app

# Usuario no-root
RUN groupadd -r devops && useradd -r -g devops devops
USER devops

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
