name: Deploy Data to EC2 Privada (MongoDB)

on:
  push:
    branches: [ "deploy" ]
    paths:
      - 'docker-compose.data.yml'
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy MongoDB via Bastion (Frontend)
        uses: appleboy/ssh-action@master
        with:
          # 1. Destino final (IP Privada de tu máquina de Datos)
          host: ${{ secrets.EC2_DATA_HOST }} 
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # 2. Configuración del Puente Bastión (Frontend Público)
          proxy_host: ${{ secrets.EC2_HOST }}        
          proxy_username: ec2-user
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}   
          
          script: |
            # Instalar herramientas básicas en la EC2 nueva de datos
            sudo dnf update -y
            sudo dnf install git docker -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user
            
            # Preparar el directorio de trabajo
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app
            
            # Inicializar el repositorio Git local dentro de la EC2 si no existe
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/benjawl-alt/Prueba2-Innovatech.git
            fi
            
            # Descargar la última estructura del Monorepo
            git fetch origin deploy
            git reset --hard origin/deploy
            
            # Levantar MongoDB usando el comando nativo moderno de Docker Compose
            sudo docker compose -f docker-compose.data.yml up -d --build