name: Deploy Backend to EC2 Privada

on:
  push:
    branches: [ "deploy" ]
    paths:
      - 'back-Ventas_SpringBoot/**'
      - 'back-Despachos_SpringBoot/**'
      - 'docker-compose.back.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend via Bastion (Frontend)
        uses: appleboy/ssh-action@master
        with:
          # 1. El destino final sigue siendo el Backend usando su IP PRIVADA
          host: ${{ secrets.EC2_BACK_HOST }} 
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # 2. CONFIGURACIÓN DEL PUENTE (PROXY/BASTIÓN)
          proxy_host: ${{ secrets.EC2_HOST }}        # <-- IP Pública de tu Frontend
          proxy_username: ec2-user
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}   # <-- Usa la misma llave .pem
          
          # 3. REGISTRO DE VARIABLES
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN
          
          script: |
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app
            
            git fetch origin deploy
            git reset --hard origin/deploy
            
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            export AWS_DEFAULT_REGION=us-east-1
            
            sudo docker-buildx install
            
            # Levantamos usando el archivo exclusivo del backend
            sudo -E docker-compose -f docker-compose.back.yml up -d --build