name: Deploy Data to EC2 Privada (MongoDB)

on:
  push:
    branches: [ "deploy" ]
    paths:
      - 'docker-compose.data.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy MongoDB via Bastion (Frontend)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DATA_HOST }} # <-- IP Privada de la Data (10.0.3.45)
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_key_transfer: true
          
          # EL PUENTE (Mismo que el anterior):
          proxy_host: ${{ secrets.EC2_HOST }} # <-- IP Pública del Frontend
          proxy_username: ec2-user
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app
            git fetch origin deploy
            git reset --hard origin/deploy
            sudo docker-buildx install
            sudo docker-compose -f docker-compose.data.yml up -d --build