name: Deploy Frontend to EC2 Pública

on:
  push:
    branches: [ "deploy" ]
  paths:
    - 'front_despacho/**'
    - 'docker-compose.front.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app
            
            # Sincronización limpia con Git
            sudo git config --global --add safe.directory /home/ec2-user/app
            sudo git fetch origin deploy
            sudo git reset --hard origin/deploy
            
            # CREACIÓN DEL .ENV USANDO TU SECRETO CORRECTO
            cat <<EOF > front_despacho/.env
            VITE_API_URL_VENTAS=http://${{ secrets.EC2_FRONTEND_PUBLIC_IP }}/api/v1/ventas
            VITE_API_URL_DESPACHOS=http://${{ secrets.EC2_FRONTEND_PUBLIC_IP }}/api/v1/despachos
            EOF
            
            # Asegurar soporte de construcción
            sudo docker-buildx install 2>/dev/null || true
            
            # Levantar el contenedor
            sudo docker compose -f docker-compose.front.yml up -d --build